Development
Ivan-Kovalev/Graduation-work pull request #14
Opened 2024-11-11 15:55 UTC by Ivan-Kovalev

2024-11-13 13:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .mvcMatchers(HttpMethod.GET, "ВСТАВЬ")
тут точно всё так и должно быть? =)

2024-11-13 13:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .hasRole(Role.ADMIN.name())
почему Get методы доступны только админу?

2024-11-13 13:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .authenticated()
Этого маловато, есть еще комментарии и т д

2024-11-13 13:21 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .anyRequest().denyAll())
Достаточно 
```
.requestMatchers("/**")
 .authenticated()
```
Фильтры применяются в порядке убывания приоритета. Если сверху есть более простые фильтры, они будут обработаны первыми. Если запрос дойдет до этого фильтра, он потребует аутентификацию.

2024-11-13 13:24 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/repository/CommentRepository.java
> +@Repository
это не нужно

2024-11-13 13:24 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/repository/UserRepository.java
> +@Repository
это не нужно

2024-11-13 13:27 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +        return new Ads(adsList.size(), adsList.toArray(new Ad[0]));
Проглядел в прошлый раз, array в спецификации означает что вы можете использовать любую коллекцию или массив.
Так что я бы поменял на лист

2024-11-13 13:28 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +        UserEntity user = userRepository.findByEmail(username).orElseThrow(() -> new UsernameNotFoundException("Ошибка! Пользователь не найден!"));
Захардкодьте все сообщения внутрь исключений, зачем писать их каждый раз

2024-11-13 13:29 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +            throw new ForbiddenActionException("Пользователь " + username + " не имеет прав удалять чужие объявления.");
А сюда просто передавайте username, само сообщение так же внутри оставьте

2024-11-13 13:31 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +        boolean isAdmin = adEntity.getAuthor().getRole().equals(Role.ADMIN);
Может быть эти проверки в отдельный утилитарный класс/бин? Или в стиле DDD пусть у самого юзера будут методы проверок? Иначе слишком часть повторяется код

2024-11-13 13:33 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +        return adMapper.mapAdEntityToAd(adEntity);
мне кажется мы меняем 1 строчку с вызовом метода на 1 строчку с вызовом метода
```

adMapper.mapAdEntityToAd(adEntity);
vs
this::mapAdEntityToAd

```
дело вкуса, можно оставить

2024-11-13 13:37 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +            userRepository.save(user);
тут нехватает return, если это будет транзакционный метод (а в проде он будет) он откатится и не сохранятся изменения

Можно перевернуть условие тогда обойдемся без return

2024-11-13 13:39 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +    public UpdateUser patchCurrentUserInfo(UpdateUser updateUser, String username) {
patch это чисто тема REST, дайте более бизнесовое название update, amend че то такое

2024-11-13 13:39 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +@Service
@Component раз это у вас не сервис а утилитарная штука

2024-11-13 13:40 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            throw new RuntimeException("Ошибка при сохранении файла");
Переписать на бизнесовый exception тут а далее, минимум на наследника

2024-11-13 13:41 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            Path filePath = directory.resolve(System.currentTimeMillis() + "-" + file.getOriginalFilename());
Это не ошибка, но  UUID.randomUUID() порандомнее. Всё таки шанс что какой-то автотест на нагрузке заспамит вас картинками с одинаковыми названиями есть

2024-11-15 13:17 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
> +@Component
это сервис

2024-11-15 13:17 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +@Component
это сервис

2024-11-15 13:17 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +@Component
и это сервис

2024-11-16 05:58 UTC, Flawden commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .mvcMatchers(HttpMethod.GET, "ВСТАВЬ")
Ошибка была устранена.

2024-11-16 05:59 UTC, Flawden commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .hasRole(Role.ADMIN.name())
Фильтры были переписаны в соответствии с требованиями.

2024-11-16 05:59 UTC, Flawden commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                                        .authenticated()
Фильтры были переписаны в соответствии с требованиями.

2024-11-16 05:59 UTC, Flawden commented on src/main/java/ru/skypro/homework/repository/CommentRepository.java
> +@Repository
Внесены требуемые корректировки

2024-11-16 06:00 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +            userRepository.save(user);
Был проведен рефакторинг метода. Исправления внесены.

2024-11-16 06:00 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +    public UpdateUser patchCurrentUserInfo(UpdateUser updateUser, String username) {
Название метода было изменено

2024-11-16 06:00 UTC, Flawden commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +@Service
Была добавлена требуемая аннотация

2024-11-16 06:01 UTC, Flawden commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            throw new RuntimeException("Ошибка при сохранении файла");
Было создано более информативное исключение.

2024-11-16 06:01 UTC, Flawden commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            Path filePath = directory.resolve(System.currentTimeMillis() + "-" + file.getOriginalFilename());
Были внесены правки. Название файла генерируется по более рандомным правилам.

2024-11-16 06:02 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
> +@Component
Аннотация была изменена в соответствии с логикой.

2024-11-16 06:02 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
> +@Component
Аннотация была изменена в соответствии с логикой.

2024-11-16 06:02 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +@Component
Аннотация была изменена в соответствии с логикой.

2024-11-16 06:02 UTC, Flawden commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +@Component
Аннотация была изменена в соответствии с логикой.

2024-11-16 06:02 UTC, Flawden commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> -                                        .mvcMatchers(HttpMethod.GET, "ВСТАВЬ")
Были внесены исправления в фильтры.

2024-11-16 12:13 UTC, AleksandrZhukovJava approved these changes

2024-11-24 14:20 UTC, AleksandrZhukovJava requested changes

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on pom.xml
> +      <version>4.30.0</version>
версию надо убрать

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on pom.xml
> +      <version>3.17.0</version>
и тут

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/controller/AdController.java
> +        if (file.getSize() > 50_000_000) {
Вынести в переменную в улитарный Enum, а еще лучше в application.properties, а еще лучше в проперти с дефолтным значением

Проверки должны быть в сервисах

HttpStatus.FORBIDDEN не подходит, технически, все не верный запросы от пользователя это BAD_REQUEST

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        boolean isAdmin = comment.getAuthor().getRole().equals(Role.ADMIN);
это как то часто мелькает, как буд-то напрашивается на отдельный метод, причем они всегда идут вместо так что можно даже убрать в один, или разделить, тут по желанию

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            return uploadDirectory.substring(18) + "/" + filePath.getFileName();
это что за костылище) как тот, кто читает код, я понятия не имею почему вдруг 18, что за число такое и откуда взялось, надо переделать.

Плюс любое изменение в пропертях потянет за собой неочевидные доработки тут

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = none
validate

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/resources/db/changelog/migrations/changelog-0.1-addUsers.yaml
> +                    nullable: true
это как у него может не быть роли

2024-11-24 14:20 UTC, AleksandrZhukovJava commented on src/main/resources/db/changelog/migrations/changelog-0.1-addUsers.yaml
> +                    nullable: false
primaryKey по умолчанию не может быть null

2024-11-24 16:16 UTC, Flawden commented on pom.xml
> +      <version>4.30.0</version>
Версия была убрана

2024-11-24 16:16 UTC, Flawden commented on pom.xml
> +      <version>3.17.0</version>
Версия была убрана

2024-11-24 16:17 UTC, Flawden commented on src/main/java/ru/skypro/homework/controller/AdController.java
> +        if (file.getSize() > 50_000_000) {
Код был исправлен и стал более релевантным

2024-11-24 16:17 UTC, Flawden commented on src/main/java/ru/skypro/homework/util/imlp/FileServiceImpl.java
> +            return uploadDirectory.substring(18) + "/" + filePath.getFileName();
Волшебство вне Хогвартса было убрано.

2024-11-24 16:17 UTC, Flawden commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = none
Исправление внесено

2024-11-24 16:18 UTC, Flawden commented on src/main/resources/db/changelog/migrations/changelog-0.1-addUsers.yaml
> +                    nullable: true
Благодарю. Ошибка была устранена

2024-11-28 09:14 UTC, merged